services:
  - type: worker
    name: mon-bot-discord # Tu peux changer ce nom si tu veux.
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        value: "METS_TON_VRAI_TOKEN_SUR_LE_SITE_DE_RENDER" # Cette valeur sera écrasée par la variable d'environnement sur Render
      - key: PYTHON_VERSION
        value: 3.11.4
